- index.js
- test/iso-i18n-countries.js
I needed to do this reverse lookup to get a code from a name, since the data is already here, it seemed logical to add this function.
The search is implemented as a simple traverse. There are probably a few ways to make this more performant but the list is not that long so this should work for most scenarios.
> Added ability to get an Alpha-2 code from a country name.

- en.js
- es.js
We received an annoyed message from a user about this - there's no need to declare ownership in any country listing, regardless.
> Remove "Province of China" from Taiwan listing

- README.md
- index.js
- package.json
- test/iso-i18n-countries.js
I needed a function that would return the ISO 3166-1 Alpha-3 code for a country. 
So, I implemented it. 😉 
Also wrote some test, to fully cover the functionality.
> Implement getAlpha3Code

- README.md
The ISO format for Sweden is SE. Currently it is marked as SV.
> mistake in ISO for Swedish. Should be SE

- langs/fr.json
- test/iso-i18n-countries.js
I think the french translation of the  ISO 3166-2 code is not correct. Today it is "France métropolitaine" but it should simply be "France".
https://www.iso.org/obp/ui/fr/#iso:code:3166:FR
https://fr.wikipedia.org/wiki/France
> fix french translation of country France

- README.md
- index.js
- package-lock.json
- package.json
- test/iso-i18n-countries.js
This commit is going to improve the range of node versions for this library without polyfill.
Replace the padStart from String, this is available only for node 8, and changed it to a simple slice.
> Remove the padStart and replace for a simple slice

- index.js
- package.json
- test/iso-i18n-countries.js
fixed isValid function for the input '...'
I think it is more bulletproof to check in the alpha2, alpha3 and numeric object than use toAlpha3 code which looks broken
> Fix is valid country code

- README.md
- index.js
- package.json
This is the pull request that closes [issue #95](https://github.com/michaelwittig/node-i18n-iso-countries/issues/95).
I've done the following:
- Added `countries.import(/** country code **/)` to simplify the register process which would inlcude requiring a json from the package first.
- Beautified the README.md with remark to make it more readable
Thanks for your attention
> Add import method to simplify register locale process

- langs/fr.json
In French, the capitalisation for United Arab Emirates was missing.
> Fix capitalisation for United Arab Emirates

- index.js
- package-lock.json
- test/iso-i18n-countries.js
Previously, the isValid function was ok with valid lowercase iso codes. A change at 3.6.2 made this behaviour change, causing a breaking change in a minor version change.
I guess that it has been inserted by mistake, so i have taken the liberty of changing that in this PR.
> Back to previous behaviour: isValid is case-insentive

- package.json
Before, this was pointing to the nonexistent `index.d.js` rather than the actually-existing `index.d.ts`.
> Fix "typings" in package.json

- langs/es.json
It's Nueva Zelanda, not Nueva Zelandia
> Fixed New Zealand translation

- langs/en.json
https://en.wikipedia.org/wiki/Libya
https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/nl_vi-11_name_change_for_libya.pdf
> Update english name for Libya

- index.d.ts
- index.js
- package-lock.json
- package.json
- test/iso-i18n-countries.js
`getSimpleAlpha2Code()` and `getSimpleAlpha3Code()` allow you to get country codes with less precise user input by ignoring diacritics (in addition to capitals).
For example, `getAlpha2Code('Belgie', 'nl')` currently returns `undefined` because the correct spelling is "België". The functions I added use [diacritic](https://www.npmjs.com/package/diacritics) to remove diacritics/accents while comparing values so they return the correct country code regardless. So now `getSimpleAlpha2Code('Belgie', 'nl')` will return `BE`.
> Retrieve alpha 2 and 3 codes ignoring diacritics

- langs/fr.json
Dear maintainers,
I run a [website that tracks Covid-19 around the world](https://covidvision.org/), and one of my reader notified me that the name for Congo (CG) was wrong in the French locale.
I have corrected it, using the data on the Wikipedia [ISO 3166-1](https://fr.wikipedia.org/wiki/ISO_3166-1) page as a source.
> Fix name of CG for fr locale

- langs/da.json
- langs/en.json
- langs/id.json
- langs/it.json
- langs/ms.json
- langs/nb.json
- langs/nn.json
- langs/ro.json
- langs/sv.json
- langs/vi.json
In 2018, "Swaziland" was officially renamed to "Eswatini":
https://en.wikipedia.org/wiki/Eswatini
https://www.bbc.com/news/world-africa-43821512
> fix: rename Swaziland to Eswatini

- langs/fr.json
- langs/nl.json
Following this PR :
https://github.com/michaelwittig/node-i18n-iso-countries/pull/170
The changes for 2 languages were missed.
Here is the fixed version for FR and NL.
https://fr.wikipedia.org/wiki/Eswatini
https://nl.wikipedia.org/wiki/Swaziland
> fix: rename Swaziland to Eswatini (FR+NL)

- index.d.ts
- index.js
- langs/pt.json
- test/iso-i18n-countries.js
Closes #174
I added test cases and updated the translation maps for the example in the issue.
```js
countries.getName("US", "pt") // Estados Unidos
countries.getAlpha2Code("Estados Unidos da América", "pt")) // US
countries.getAlpha2Code("Estados Unidos", "pt")) // US
countries.getSimpleAlpha2Code("Estados Unidos da America", "pt")) // US
```
---
While building this, I found the code a little hard to follow, using `var` everywhere. I changed this bits to use `const` instead (supported since Node 6)
> feat: Allow alternative country name spellings via array

- .travis.yml
- package.json
Related to https://github.com/michaelwittig/node-i18n-iso-countries/issues/176
https://nodejs.org/en/about/releases/
- Node 8 is not maintained 
- Node 14 is in current development
- Node 13 will be deprecated on 2020-06-01
I also made sure we are following Travis' latest build config:
> chore: Drop Node 8, include Node 14

- langs/pt.json
Since 2009, in Portuguese [Cingapura is wrong, Singapura is correct](https://duvidas.dicio.com.br/singapura-ou-cingapura/#:~:text=A%20forma%20correta%20de%20escrita,Ortogr%C3%A1fico%2C%20em%20janeiro%20de%202009.). But many places still write the country name with C.
So, I added the alternative name so people can still search it when writing with C.
> fix: Update Portuguese name for Singapore

- langs/sv.json
The Swedish Ministry of Foreign affairs changed from Vitryssland (literal translation of Belarus to swedish) to Belarus on 11th November 2019. Source: https://www.svt.se/nyheter/utrikes/regeringen-vitryssland-blir-belarus (SVT is swedish public service news channel)
> Change name of Belarus in sv.json from Vitryssland to Belarus

- .eslintrc
- index.js
- package.json
Should fix #214. Also add some minor tweaks as I am using Windows 10 with Git Bash to contribute.
By the way, `var` is a bit general so switched those to `const` as pretty much the country code objects should be constants by default.
> Fix function call references

- .github/workflows/ci.yml
Sets up GitHub Actions to test every Pull Request and Push on multiple node versions:
- LTS: 10, 12, 14
- Current: 15
This is in preparation of the upcoming Typescript and infrastructure changes which might impact Node 10 and 15 users
> ci: Node versions matrix

- langs/fr.json
Added missing diaeresis for french Azerbaijan orthography.
> fix: french Azerbaijan orthography

- index.d.ts
Typo fix: "contry" => "country"
> Fix typo in TS types

- langs/en.json
I changed the name of Palestine to the official one in accordance with
https://www.iso.org/obp/ui/#iso:code:3166:PS
or 
https://en.wikipedia.org/wiki/State_of_Palestine
> Change the name of Palestine to the official one

- langs/de.json
Follow up to #170 and #171: Renaming also applies to German. Unfortunately, I don't know about any other languages.
> Rename Swaziland to Eswatini (DE)

- langs/en.json
There was a typo in the country name appearing at the signup form. Country name Iran was written as "Iran, Islamic Republic of" which is converted to "Islamic Republic of Iran".
> en: Country name Iran corrected

- README.md
The `select` option is currently not really documented as all examples use `official` and you will have to read the code to find out about a. what other options there are and b. what they do.
This PR adds a section about how to use the option to the README.
See #253
> Add documentation on select option

- langs/it.json
This PR adds an alternative name for `TW` (Taiwan) to Italian language. Unlike most other languages that offer also/only "Taiwan" as a name, the only option so far in Italian was "Repubblica di Cina".
> feat: add alternative name for taiwan in IT

- langs/en.json
The name of the country North Macedonia was written as "North Macedonia, Republic of". Which was incorrect. I changed it to ["The Republic of North Macedonia","North Macedonia"]. Now we have 2 variants of it.
> North Mecedonia Name Corrected

- langs/es.json
In Spanish language, country name Iran was written as "Irán (República Islámica de)". Which was incorrect. Now changed it to ["Irán", "República Islámica de Irán"]. Now we have 2 variants of it.
> Iran name update in spanish language

- langs/en.json
The name of the country Congo was written as "Congo, the Democratic Republic of the". Which was incorrect. I changed it to ["Congo", "Democratic Republic of the Congo"]. Now we have 2 variants of it.
> Country name Congo corrected

- langs/en.json
Add Czechia as an alternative English name for Czech Republic
> Add alternative English name for Czech Republic

- langs/en.json
Though the country changed it's official name i think it is appropriate to keep in "turkey" as it is commonly used by users
> Added back "turkey"

- index.d.ts
Several functions return `undefined`, but they are defined as returning `string` always.
This tries to fix all the use cases I found, but there might be more.
Here are some examples:
https://github.com/michaelwittig/node-i18n-iso-countries/blob/cf01cdadefc7758dcf9faf50186200cd8720a700/index.js#L227
https://github.com/michaelwittig/node-i18n-iso-countries/blob/cf01cdadefc7758dcf9faf50186200cd8720a700/index.js#L227
> fix: undefined as return type is missing

- langs/de.json
This PR adds an alias, `Hong Kong`, for the German language.
Closes #196
> feat(de): add Hong Kong alias
